{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_report_allure_demo1.py:13: AssertionError"}, "description": "this test fails", "start": 1613568330126, "stop": 1613568330126, "uuid": "80e91287-cb45-451e-a9b4-5558d64106f6", "historyId": "b964f12c4559b6c5a5971a6e964bd2ea", "testCaseId": "c9a89e20c743a11953628a31245b5879", "fullName": "test_report_allure_demo1#test_failure", "labels": [{"name": "suite", "value": "test_report_allure_demo1"}, {"name": "host", "value": "DESKTOP-39CMD4K"}, {"name": "thread", "value": "32908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_report_allure_demo1"}]}